name: Release with Archives
on:
  push:
    tags:
      - "v*"  # 匹配 v1.0.0, v2.3.4 等格式的标签

permissions:
  contents: write  # 确保有写权限

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          draft: false
          prerelease: false