name: Release with Archives
on:
  push:
    tags:
      - "v*"  # 匹配 v1.0.0, v2.3.4 等格式的标签
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create ZIP archive (excluding .git, .github, .gitignore)
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          zip -r WeChatSync-$VERSION.zip . \
            -x ".git/*" \
            -x ".github/*" \
            -x ".gitignore" \
            -x "*.DS_Store"  # 可选：排除 macOS 的 .DS_Store 文件

      - name: Create TAR.GZ archive (excluding .git, .github, .gitignore)
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          tar -czvf WeChatSync-$VERSION.tar.gz . \
            --exclude=".git" \
            --exclude=".github" \
            --exclude=".gitignore" \
            --exclude="*.DS_Store"  # 可选：排除 macOS 的 .DS_Store 文件

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload ZIP to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./WeChatSync-$VERSION.zip
          asset_name: WeChatSync-$VERSION.zip
          asset_content_type: application/zip

      - name: Upload TAR.GZ to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./WeChatSync-$VERSION.tar.gz
          asset_name: WeChatSync-$VERSION.tar.gz
          asset_content_type: application/gzip
